#!/usr/bin/php
<?php
/**
 * Axo - Console Micro-Framework
 *
 * @author Adam Prickett <adam.prickett@ampersa.co.uk>
 * @license MIT
 * @copyright © Copyright Ampersa Ltd 2017.
 */

require 'vendor/autoload.php';

define('AXO_PATH', rtrim(dirname(__FILE__), '/').'/');

// Load .env configuration
$dotenv = new Dotenv\Dotenv('./');
$dotenv->load();

// Load to Console Application and run
$app = new System\Axo;
$app->addCommandDirectory('./commands', 'Commands');
$app->run();

return;
