#!/usr/bin/php
<?php
/**
 * Console App Framework
 *
 * @author Adam Prickett <adam.prickett@gmail.com>
 * @license MIT
 * @copyright © Copyright Adam Prickett 2016.
 */

require 'vendor/autoload.php';

date_default_timezone_set('Europe/London');

define('FRONT_CONTROLLER_PATH', rtrim(dirname(__FILE__), '/').'/');

$dotenv = new \Dotenv\Dotenv('./');
$dotenv->load();

$arguments = $_SERVER['argv'];

// The first argument wil simply be this script name
array_shift($arguments);

// Load to Console Application and run
$app = new System\ConsoleApplication;
$app->run($arguments);

return;
