#!/usr/bin/php
<?php
/**
 * Console App Framework
 *
 * @author Adam Prickett <adam.prickett@gmail.com>
 * @license MIT
 * @copyright © Copyright Adam Prickett 2017.
 */
require 'vendor/autoload.php';

date_default_timezone_set('Europe/London');

define('FRONT_CONTROLLER_PATH', rtrim(dirname(__FILE__), '/').'/');

// Load .env configuration
$dotenv = new Dotenv\Dotenv('./');
$dotenv->load();

// Load to Console Application and run
$app = new System\ConsoleApplication;
$app->run();

return;
